A0-2548 Initialization for aleph pallet
Cardinal-Cryptography/aleph-parachain-bridge pull request #2
Opened 2023-05-26 13:26 UTC by krzysztofziobro

2023-05-29 12:05 UTC, obrok requested changes

2023-05-29 12:05 UTC, obrok commented on .github/workflows/test-code.yml
> +    - name: Install toolchain
Request: Use the action from https://github.com/Cardinal-Cryptography/github-actions/tree/main/install-rust-toolchain instead (it supports `rust-toolchain.toml`). Move the `components` and `target` spec into `rust-toolchain.toml`.

2023-05-29 12:05 UTC, obrok commented on .github/workflows/test-code.yml
> +    - name: Check and Lint Code
Request: add a format check.

2023-05-29 12:05 UTC, obrok commented on modules/aleph/src/lib.rs
> +// along with Parity Bridges Common.  If not, see <http://www.gnu.org/licenses/>.
Question: Should a parity license be here? I assume this file is not just a copy-paste of their code, but is customized for our usecase.

2023-05-29 12:05 UTC, obrok commented on modules/aleph/src/lib.rs
> +// This pallet is largely based on the `GRANDPA` pallet, is changed to work with AlephBFT
```suggestion
// This pallet is largely based on the `GRANDPA` pallet, but is changed to work with AlephBFT
```

2023-05-29 12:05 UTC, obrok commented on modules/aleph/src/lib.rs
> +// Runtime-generated enums
```suggestion
```

IMO Useless comment

2023-05-29 12:05 UTC, obrok commented on modules/aleph/src/lib.rs
> +/// The target that will be used when publishing logs related to this pallet.
Suggestion: remove comment, it just says the same thing as the line below.

2023-05-29 12:05 UTC, obrok commented on modules/aleph/src/lib.rs
> +/// Header data of the bridged chain that is stored at this chain by this pallet.
Suggestion: Same with these comments, they don't really add any new information.

2023-05-29 12:05 UTC, obrok commented on modules/aleph/src/lib.rs
> +		/// change if it is already know.
```suggestion
		/// change if it is already known.
```

2023-05-29 12:05 UTC, obrok commented on modules/aleph/src/lib.rs
> +	/// A ring buffer of imported hashes. Ordered by the insertion time.
```suggestion
	/// A ring buffer of imported hashes. Ordered by insertion time.
```

2023-05-29 12:05 UTC, obrok commented on modules/aleph/src/lib.rs
> +	/// Pallet owner has a right to halt all pallet operations and then resume it. If it is
```suggestion
	/// Pallet owner has the right to halt all pallet operations and then resume them. If it is
```

2023-05-29 12:05 UTC, obrok commented on modules/aleph/src/lib.rs
> +	pub(crate) fn initialize_bridge<T: Config<I>, I: 'static>(
Question: shouldn't this be private since it has a pretty hard precondition?

2023-05-29 12:05 UTC, obrok commented on modules/aleph/src/mock.rs
> +// along with Parity Bridges Common.  If not, see <http://www.gnu.org/licenses/>.
Same here with the license?

2023-05-29 12:05 UTC, obrok commented on modules/aleph/src/storage_types.rs
> +// along with Parity Bridges Common.  If not, see <http://www.gnu.org/licenses/>.
Same here with the license?

2023-05-29 12:05 UTC, obrok commented on modules/aleph/src/storage_types.rs
> +/// A list of AlephBFT authorities.
```suggestion
```

IMO useless comment

2023-05-29 12:05 UTC, obrok commented on primitives/aleph-header-chain/src/lib.rs
> +// along with Parity Bridges Common.  If not, see <http://www.gnu.org/licenses/>.
Same here with the license?

2023-05-29 12:05 UTC, obrok commented on primitives/aleph-header-chain/src/lib.rs
> +	/// `pallet-bridge-aleph::Call::initialize`
```suggestion
```

leftovers?

2023-05-29 12:05 UTC, obrok commented on primitives/aleph-header-chain/src/lib.rs
> +/// The `BridgeAlephCall` used by a chain.
```suggestion
```

IMO useless comment

2023-06-29 14:27 UTC, krzysztofziobro commented on primitives/aleph-header-chain/src/lib.rs
> +// along with Parity Bridges Common.  If not, see <http://www.gnu.org/licenses/>.
Edited the notices

2023-06-30 11:06 UTC, krzysztofziobro commented on modules/aleph/src/lib.rs
> +// along with Parity Bridges Common.  If not, see <http://www.gnu.org/licenses/>.
We have to keep it and mark that this version is modified

2023-07-03 13:14 UTC, mike1729 requested changes

2023-07-03 13:14 UTC, mike1729 commented on primitives/aleph-header-chain/src/lib.rs
> +pub const KEY_TYPE: KeyTypeId = KeyTypeId(*b"alp0");
Is there some reason to not pull such params from aleph-node?

2023-07-03 13:14 UTC, mike1729 commented on modules/aleph/src/lib.rs
> +			Ok(().into())
Beautiful :rofl:

2023-07-03 13:16 UTC, mike1729 requested changes

2023-07-03 13:16 UTC, mike1729 commented on modules/aleph/src/lib.rs
> +mod tests {
One important test is missing: a test for `insert_header`.

2023-07-04 11:41 UTC, krzysztofziobro commented on primitives/aleph-header-chain/src/lib.rs
> +pub const KEY_TYPE: KeyTypeId = KeyTypeId(*b"alp0");
I had problems with dependencies from aleph-node

2023-07-04 11:45 UTC, mike1729 commented on primitives/aleph-header-chain/src/lib.rs
> +pub const KEY_TYPE: KeyTypeId = KeyTypeId(*b"alp0");
Oh, right. Better leave as is then :sweat:

2023-07-24 10:40 UTC, mike1729 approved these changes

2023-08-10 14:36 UTC, obrok approved these changes

2023-08-10 14:36 UTC, obrok commented on modules/aleph/src/lib.rs
> +		pub(crate) fn insert_header(header: BridgedHeader<T>) {
Question: Does this need to be `pub`?

2023-08-10 14:36 UTC, obrok commented on modules/aleph/src/lib.rs
> +	// We need to use it since `StorageMap` implementation expects Get<Option<u32>> for `MaxValues`.
```suggestion
	/// We need to use it since `StorageMap` implementation expects Get<Option<u32>> for `MaxValues`.
```

2023-08-10 14:36 UTC, obrok commented on modules/aleph/src/mock.rs
> +
Suggestion - add a module doc for what this file is for and how to use it.

2023-08-10 14:54 UTC, krzysztofziobro commented on modules/aleph/src/lib.rs
> +		pub(crate) fn insert_header(header: BridgedHeader<T>) {
For testing purposes

2023-08-16 11:11 UTC, obrok approved these changes

2023-08-16 11:17 UTC, merged