A0-2550 Aleph bridge pallet: submitting proofs
Cardinal-Cryptography/aleph-parachain-bridge pull request #6
Opened 2023-07-07 10:01 UTC by krzysztofziobro

Adding a `submit_finality_proof` call along with some tests.

This should make the first usable version of this pallet, but the weights are incorrect: will need to be properly set in a separate PR.

2023-07-24 11:15 UTC, mike1729 commented on modules/aleph/src/lib.rs
> +		/// Header is older than the last imported header.
The new description doesn't match the error name.

2023-07-25 08:54 UTC, krzysztofziobro commented on modules/aleph/src/lib.rs
> +		/// Header is older than the last imported header.
fixed

2023-08-01 11:02 UTC, obrok requested changes
I'm trying to move everything to the `aleph-parachain` repo, so that it doesn't have all the parity baggage. I think this PR should be migrated over there - I'll do it at some point if you don't do it before me.

2023-08-16 14:35 UTC, obrok approved these changes

2023-08-16 14:35 UTC, obrok commented on modules/aleph/src/lib.rs
> +		pub(crate) fn try_enact_authority_change(
Suggestion: make this private.

2023-08-16 14:35 UTC, obrok commented on modules/aleph/src/lib.rs
> +		) -> Result<bool, Error<T>> {
Suggestion: it seems we're never using the `bool` from this function, make this return `Result<(), Error<T>>`

2023-08-16 14:35 UTC, obrok commented on primitives/aleph-header-chain/src/lib.rs
> +pub fn get_authority_change(digest: &Digest) -> Option<AuthoritySet> {
Question: why is this function in this particular library?

2023-08-17 10:00 UTC, krzysztofziobro commented on primitives/aleph-header-chain/src/lib.rs
> +pub fn get_authority_change(digest: &Digest) -> Option<AuthoritySet> {
It can be reused to implement `ConsensusLogReader` required for `Engine` implementation, so I didn't want to put it into pallet specific code.

2023-08-17 10:05 UTC, krzysztofziobro commented on modules/aleph/src/lib.rs
> +		pub(crate) fn try_enact_authority_change(
done

2023-08-17 10:05 UTC, krzysztofziobro commented on modules/aleph/src/lib.rs
> +		) -> Result<bool, Error<T>> {
done

2023-08-18 13:01 UTC, merged